---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filemanager-admin
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filemanager-admin
  namespace: filemanager
roleRef:
  kind: ClusterRole
  name: filemanager-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filemanager-admin
  namespace: filemanager
