# go-gcs/deploy/helm/apps
apps:
  # go-gcs/deploy/helm/apps/charts/filemanager-server
  filemanager:
    controller:
      replicaCount: 1
      image: gcr.io/jello-stage-223210/file-manager
      apiserverImageTag: latest
      imagePullPolicy: Always
      timestamp: 0
    app:
      config: staging.json
    service:
      ports:
        apiserverNodePort: 32326
    ingress:
      cert: "dev-jellotalk-com"
      ipName: "lb-stg-file-gke"
