apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemanager-server
  namespace: filemanager
  labels:
    app: filemanager-server
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: filemanager-server
  template:
    metadata:
      labels:
        app: filemanager-server
    spec:
      serviceAccountName: filemanager-admin
      containers:
      - name: filemanager-server
        image: {{ .Values.controller.image }}:{{ .Values.controller.apiserverImageTag }}
        imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
        ports:
        - containerPort: 7890
        volumeMounts:
        - name: config-volume
          mountPath: /go-gcs/config/{{ .Values.app.config }}
          subPath: {{ .Values.app.config }}
          readOnly: true
      volumes:
        - name: config-volume
          secret:
            secretName: filemanager-config
