- name: Install rsync
  become: True
  yum:
    name: rsync

- name: Create directory
  file:
    path: "{{ app_dest }}"
    state: directory

- set_fact:
    config_dir: "{{ app_dest }}/config"

- name: Create the config directory
  file:
    path: "{{ config_dir }}"
    state: directory

- name: Copy files to "{{ app_dest }}"
  synchronize:
    src: "./common/"
    dest: "{{ app_dest }}"
    copy_links: yes

- name: Copy files to "{{ app_dest }}" for "{{ env }}"
  synchronize:
    src: "./{{ env }}/"
    dest: "{{ config_dir }}"
    copy_links: yes

- name: Create file_manager.service
  become: True
  template: src=file_manager.service.j2 dest="/etc/systemd/system/file_manager.service"

- name: Restart file_manager.service
  become: True
  systemd:
    state: restarted
    daemon_reload: yes
    name: file_manager.service
  register: start_file_manager_server_res

- name: Wait for {{ app_name }} to start
  wait_for:
    port: "{{ app_port }}"
    timeout: 10
